### ISSUE TITLE
Matplotlib in abtools

### ISSUE THREAD

**Issue by jwillis0720** [briney/abstar#13]
Might I make a suggestion to change the **init** file to only import mpl on the utilities which require mpl. And thus it's taking 25 seconds to import this library every time I clean and reload abstar. Also, when I grep for "^mpl" I don't see it being used. However I do see seaborn used quite heavily.

**Comment by briney** [comment]
It's only in __init__ as a stopgap. Trying to save figures will often fail on AWS machines because there's no $DISPLAY, and the default mpl renderer requires it. Importing pyplot sets the mpl renderer as the default, so I need to ensure that mpl.use('Agg') gets called before I import pyplot anywhere.
